### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by rot1024** [archival-archetyping/about-widget-reearth-plugin#2]
Thanks for developing this great plugin! 

Can you add LICENSE file to clarify the OSS license? (e.g. MIT License, Public Domain)

**Comment by kotobuki** [comment]
@rot1024 
Thank you very much for asking. We chose the MIT License. 😉

Please find the LICENSE file at:
https://github.com/archival-archetyping/about-widget-reearth-plugin/blob/main/LICENSE

**Comment by rot1024** [comment]
Thank you!
